name: Build and publish filebrowser image to GHCR

on:
  # Run this worflow on demand
  workflow_dispatch:
  # Or at 01:05:00 Tuesday (UTC)
  schedule:
    - cron: '5 1 * * 3'
  push:
    branches: "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository_owner }}/filebrowser"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        conf: 
          - version: "2.22.4"
            latest: true
          - version: "2.21.1"
            latest: false
          - version: "2.20.1"
            latest: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,${{ matrix.conf.version }}
            ${{ matrix.conf.latest && 'type=raw,latest' || '' }}
            ${{ matrix.conf.latest && 'type=raw,2' || '' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: FILEBROWSER_VERS=v${{ matrix.conf.version }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
